### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by PaulCarrascosa** [ntorquet/lmt_toolkit_analysis#51]
Hello @ntorquet, I have few questions about the install process !

First, I create the virtual env using 'python -m venv \path\to\the\root\folder\' and it seems to work properly than 'virtualenv venv' (I don't know why).

Then, I've tried to change the 'manage.py' file from the 'lmt_toolkit_analysis-main' folder with the file from the 'lmt_toolkit_analysis-dev'. Doing this, the 'python manage.py loaddata fixtures/datatostart.json' works (I don't know why) !

Moreover, is it normal that when I launch the Django server, I have a Page Not Found (404), even with the 'http://127.0.0.1:8000/' ?

For the moment, when I do it like this, the first error is when I try to launch Celery (again), but it will work !

Thanks a lot for your help.
Cheers,
Paul

**Comment by ntorquet** [comment]
Hi @PaulCarrascosa ,

>First, I create the virtual env using 'python -m venv \path\to\the\root\folder' and it seems to work properly than 'virtualenv venv' (I don't know why).

As often the case, there are several ways of doing this, but it's strange that `virtualenv venv` doesn't work. The important thing is that it works for you :wink:

>Then, I've tried to change the 'manage.py' file from the 'lmt_toolkit_analysis-main' folder with the file from the 'lmt_toolkit_analysis-dev'. Doing this, the 'python manage.py loaddata fixtures/datatostart.json' works (I don't know why) !

Ok, this is also strange... in theory, there is no difference between these two files. But again, if it works for you...

> Moreover, is it normal that when I launch the Django server, I have a Page Not Found (404), even with the 'http://127.0.0.1:8000/' ?

This is normal because this is a Django-Rest application. You can try 'http://127.0.0.1:8000/api/v1/': you should see the api interface.

For Celery, the problem comes from the RabbitMQ installation right?

Cheers,
Nicolas

**Comment by ntorquet** [comment]
Problems solved. See this issue #40
